version:  "3"
    
services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/conf.d/:/etc/nginx/conf.d
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nest

networks:
  nest:
    name: nest
    driver: bridge